Molecules plan
shinonome-inc/Ren-Yagi-frontend-basic-last-assignment pull request #6
Opened 2022-06-26 03:37 UTC by renyagi

## セルフチェック
- [〇] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [〇] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [〇] 記述の重複はないか

リンク
[https://628afc777989ea004a1f43f6-wzkkfvzjct.chromatic.com/?path=/story/molecules-plan--example](chromatic上の該当ページへのリンクを貼る)

2022-06-26 14:43 UTC, Hasegawa62 reviewed
タグの変更、横幅の指定を減らすことで必要のなくなる記述がたくさんできると思うのでそちらも確認してみてください！
また、偶数奇数でスタイルが変わるplanを2つ作りましょう。

2022-06-26 14:43 UTC, Hasegawa62 commented on src/components/molecules/plan/plan.scss
> +      padding: 20px 40px;
横幅は画面や親要素の大きさに合わせて変化できるようにしておきましょう。
paddingではなく他の方法で横中央揃えをしてみてください。

2022-06-26 14:43 UTC, Hasegawa62 commented on src/components/molecules/plan/plan.html
> +  <li class="list-group-item list1">プランテキスト</li>
class名からどんな要素かわかるような名前を付けてあげてください。

2022-06-26 14:43 UTC, Hasegawa62 commented on src/components/molecules/plan/plan.html
> +      <p class="p2-1">¥</p>
pタグは段落を示す意味のあるタグであり、ここにはあまり適していないと思います。
他のタグが使えないか探してみてください。

2022-07-02 14:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.scss
> +    .cost {
文字が細いです

2022-07-02 14:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.scss
> +  .plan-price {
ここと`.plan-span`との間隔を開けてください

2022-07-02 14:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.scss
> +      text-align: right;
これ必要ですか？

2022-07-02 14:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.scss
> +    .plan-information {
これ適用されていない気がします

2022-07-02 14:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.scss
> +.list-group:nth-child(even) {
入れ子で書いてほしいです！
それと偶数の時の見た目で変更が欲しい分だけ書けばよいです

2022-08-02 03:07 UTC, renyagi commented on src/components/molecules/plan/plan.scss
> +      text-align: right;
font-sizeの値が違うので必要だと思いました！

2022-08-02 09:18 UTC, KEISUKE0293 reviewed
修正してください！

2022-08-02 09:18 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.html
> +  <li class="list-group-item plan-name">プランテキスト</li>
ここの文字の太さが違います！

2022-08-02 09:18 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.scss
> +    margin-top: 10px;
このmargin-topは何でしょうか？
もしorganismsのことを考えた余白なのであれば数値が違うので直してください！（あと下に指定しなおした方が良いかもしれません）

2022-08-02 09:18 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.scss
> +      padding-bottom: 15.5px;
まとめて書いてみてください！

2022-08-02 09:18 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.scss
> +    padding-top: 24px;
まとめて書いてください！（paddingについて）

2022-08-02 09:18 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.scss
> +    padding-bottom: 20px;
まとめて書いてください！

2022-08-02 09:18 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.scss
> +    padding-bottom: 20px;
まとめて書いてください！

2022-08-03 06:15 UTC, renyagi commented on src/components/molecules/plan/plan.scss
> +    margin-top: 10px;
デイタイムプランとスタンダードプランの間に幅をつけるためにつけました。なので、値は適当だったのですが、organismのことを考えて数値を変えました。

2022-08-03 10:37 UTC, KEISUKE0293 reviewed
padding１つに直してもらったんですけど、左右の値にある1%は何か意味していますか？
そこだけ教えてほしいです！

では、修正お願いします！

2022-08-03 10:37 UTC, KEISUKE0293 commented on src/components/molecules/plan/plan.scss
> +    margin-top: 24px;
このままだと2個目と3個目との余白ができないので、別の書き方で余白を実現してみてください！

2022-08-05 04:47 UTC, MoAI522 commented on src/components/molecules/plan/plan.html
> +<ul class="list-group">
list-groupという名前だと何のコンポーネントか分かりづらいので、planとかにしときましょう。
コンポーネントの一番外側のクラス名は、別のコンポーネントと区別がつくようにした方がよいです。

2022-08-05 04:47 UTC, MoAI522 commented on src/components/molecules/plan/plan.html
> +      <span class="¥">¥</span>
クラス名でハイフン以外の記号を使うのは危なっかしいのでやめましょう。
記号があると一瞬何か特殊な文法のように見えてしまいます。

2022-08-05 04:47 UTC, MoAI522 commented on src/components/molecules/plan/plan.scss
> +    padding: 20px 0% 20px;
ついでに修正していただきたいのですが、意味ありげに見えてしまって紛らわしいので0%でなくて0にしましょう。他の箇所も同様です。

2022-08-08 04:05 UTC, haruchu commented
文字数が多い時のためにも横に余白が欲しいです
<img width="611" alt="スクリーンショット 2022-08-08 13 05 02" src="https://user-images.githubusercontent.com/66406382/183336822-d9ed6994-42c7-47d2-a6e2-c96f858552b0.png">

2022-08-08 04:06 UTC, haruchu commented on src/components/molecules/plan/plan.html
> +      <span class="cost-mark">¥</span>
こちら疑似要素を用いて書いたりできますか？

2022-08-09 03:41 UTC, renyagi commented on src/components/molecules/plan/plan.html
> +      <span class="cost-mark">¥</span>
疑似要素を用いた書き方が思い付かないです。
すみません。

2022-08-09 08:39 UTC, haruchu commented on src/components/molecules/plan/plan.html
> +      <span class="cost-mark">¥</span>
https://www.asobou.co.jp/blog/web/css2
参考にしてみてください！

2022-08-09 08:40 UTC, haruchu commented
コメントしました！
https://github.com/shinonome-inc/Ren-Yagi-frontend-basic-last-assignment/pull/6#discussion_r941065165

2022-08-14 16:01 UTC, higashiji2000 requested changes
marginの方のみ必須対応ということでお願いします！

2022-08-14 16:01 UTC, Higashiji commented on src/components/molecules/plan/plan.scss
> +    margin: 24px 0;
![image](https://user-images.githubusercontent.com/83479175/184544995-aed86bc2-6517-4e38-b665-c479e40d8898.png)
marginをこのように設定してしまうと横並びにしたときに問題があります。
余白の調整は orgainsims/plans で行うとして、このPRでは考えなくて大丈夫です。

2022-08-14 16:01 UTC, Higashiji commented on src/components/molecules/plan/plan.scss
> +  }
![image](https://user-images.githubusercontent.com/83479175/184545071-46fc5c1b-6956-4735-b5f5-92fdfc501a66.png)
横並びにしたときに線がずれちゃっているので、可能ならそろえてみてください。
[元サイト](https://demo.tcd-theme.com/tcd063/)の実装が参考になると思います。

2022-08-17 04:05 UTC, higashiji2000 approved these changes
LGTMです

2022-08-17 04:05 UTC, higashiji2000 commented on src/components/molecules/plan/plan.scss
> +    color: $black;
この辺の色の指定はなくても大丈夫です！

2022-08-17 13:06 UTC, merged